### ISSUE TITLE
How to get html text with font?

### ISSUE THREAD

**Issue by hagile** [nnhubbard/ZSSRichTextEditor#105]
I'm using `[self getHTML]` of `ZSSRichTextEditor` to get html string. Its works great. But now at point, I need to set font for the same text and to get html text belonging to that particular font. Is it possible? Any luck?

**Comment by nnhubbard** [comment]
I can't think of a way that you could do this without some additional features being added.

**Comment by hagile** [comment]
I'm not getting you.

Currently, you have set some font for the textview. But when I get the text out of it, its not containing font inside that html? And when I use, `setHTML:` method to set html text back, it also works well. So this is something strange. Any thoughts on this?

**Comment by hagile** [comment]
@nnhubbard, please check this Stackoverflow link for more details: http://stackoverflow.com/questions/33758040/how-to-format-html-string-with-font-for-zssrichtexteditor

**Comment by nnhubbard** [comment]
The editor is styled using the following:

```css
* {outline: 0px solid transparent; -webkit-tap-highlight-color: rgba(0,0,0,0); -webkit-touch-callout: none;}
html, body {padding:0; margin:0; font-family:Arial, Helvetica, sans-serif;}
body {padding:10px; overflow-y: scroll; -webkit-overflow-scrolling: touch; height:100%;}
```

This is the same thing that and browser does, is set some default styling for the content.
